// Stub components - placeholders for future features
// Accept any props to avoid TypeScript errors
export const EditorialAttractions = (_props: any) => null;
export const FeaturedAttractions = (_props: any) => null;
export const TopPOIs = (_props: any) => null;
export const EditorialNews = (_props: any) => null;
export const UpcomingEvents = (_props: any) => null;
export const UpcomingHolidays = (_props: any) => null;
export const SafetyBanner = (_props: any) => null;
export const QuickInfoRail = (_props: any) => null;
export const GettingAround = (_props: any) => null;
export const DestinationFAQ = (_props: any) => null;
export const DestinationCTA = (_props: any) => null;
