/**
 * Role-based permissions for the CMS
 * Extracted from shared/schema.ts for modular imports
 */

export const ROLE_PERMISSIONS = {
  admin: {
    canCreate: true,
    canEdit: true,
    canEditOwn: true,
    canDelete: true,
    canPublish: true,
    canSubmitForReview: true,
    canManageUsers: true,
    canManageSettings: true,
    canViewAnalytics: true,
    canViewAuditLogs: true,
    canAccessMediaLibrary: true,
    canAccessAffiliates: true,
    canViewAll: true,
    canEditPageSeo: true,
  },
  editor: {
    canCreate: true,
    canEdit: true,
    canEditOwn: true,
    canDelete: false,
    canPublish: true,
    canSubmitForReview: true,
    canManageUsers: false,
    canManageSettings: false,
    canViewAnalytics: true,
    canViewAuditLogs: false,
    canAccessMediaLibrary: true,
    canAccessAffiliates: true,
    canViewAll: true,
    canEditPageSeo: true,
  },
  author: {
    canCreate: true,
    canEdit: false,
    canEditOwn: true,
    canDelete: false,
    canPublish: false,
    canSubmitForReview: true,
    canManageUsers: false,
    canManageSettings: false,
    canViewAnalytics: false,
    canViewAuditLogs: false,
    canAccessMediaLibrary: false,
    canAccessAffiliates: false,
    canViewAll: false,
    canEditPageSeo: false,
  },
  contributor: {
    canCreate: true,
    canEdit: false,
    canEditOwn: true,
    canDelete: false,
    canPublish: false,
    canSubmitForReview: true,
    canManageUsers: false,
    canManageSettings: false,
    canViewAnalytics: false,
    canViewAuditLogs: false,
    canAccessMediaLibrary: false,
    canAccessAffiliates: false,
    canViewAll: false,
    canEditPageSeo: false,
  },
  viewer: {
    canCreate: false,
    canEdit: false,
    canEditOwn: false,
    canDelete: false,
    canPublish: false,
    canSubmitForReview: false,
    canManageUsers: false,
    canManageSettings: false,
    canViewAnalytics: false,
    canViewAuditLogs: false,
    canAccessMediaLibrary: false,
    canAccessAffiliates: false,
    canViewAll: true,
    canEditPageSeo: false,
  },
} as const;

export type UserRole = "admin" | "editor" | "author" | "contributor" | "viewer";
export type RolePermissions = (typeof ROLE_PERMISSIONS)[UserRole];
