/**
 * Central Metrics Registry - Metric Definitions
 *
 * Single source of truth for ALL metrics in the platform.
 * Every metric must be defined here before use.
 *
 * Naming Convention: category.metric_name
 * Examples: engagement.page_views, seo.ctr, revenue.booking_value
 */

import type { MetricDefinition } from './types';

// =====================================================
// ENGAGEMENT METRICS
// =====================================================

export const ENGAGEMENT_METRICS: MetricDefinition[] = [
  {
    id: 'engagement.page_views',
    name: 'Page Views',
    description: 'Total number of page views',
    category: 'engagement',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['realtime', 'hour', 'day', 'week', 'month'],
    entityTypes: ['content', 'destination', 'system'],
    source: 'database',
    dashboards: ['all'],
    format: { decimals: 0 },
  },
  {
    id: 'engagement.unique_visitors',
    name: 'Unique Visitors',
    description: 'Number of unique visitors',
    category: 'engagement',
    type: 'counter',
    unit: 'count',
    aggregation: 'count',
    granularity: ['hour', 'day', 'week', 'month'],
    entityTypes: ['content', 'destination', 'system'],
    source: 'database',
    dashboards: ['all'],
    format: { decimals: 0 },
  },
  {
    id: 'engagement.session_duration',
    name: 'Average Session Duration',
    description: 'Average time spent per session in seconds',
    category: 'engagement',
    type: 'duration',
    unit: 'seconds',
    aggregation: 'avg',
    granularity: ['hour', 'day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    thresholds: {
      warning: 30,
      critical: 15,
      direction: 'below',
    },
    source: 'database',
    dashboards: ['pm', 'seo'],
    format: { decimals: 0, suffix: 's' },
  },
  {
    id: 'engagement.bounce_rate',
    name: 'Bounce Rate',
    description: 'Percentage of single-page sessions',
    category: 'engagement',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'destination', 'system'],
    thresholds: {
      warning: 70,
      critical: 85,
      direction: 'above',
    },
    source: 'calculated',
    dashboards: ['seo', 'pm'],
    format: { decimals: 1, suffix: '%' },
    formula: '(single_page_sessions / total_sessions) * 100',
  },
  {
    id: 'engagement.dwell_time',
    name: 'Average Dwell Time',
    description: 'Average time on page before leaving',
    category: 'engagement',
    type: 'duration',
    unit: 'seconds',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content'],
    thresholds: {
      warning: 30,
      critical: 15,
      direction: 'below',
    },
    source: 'database',
    dashboards: ['seo', 'pm'],
    format: { decimals: 0, suffix: 's' },
  },
  {
    id: 'engagement.scroll_depth',
    name: 'Average Scroll Depth',
    description: 'Average percentage of page scrolled',
    category: 'engagement',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content'],
    thresholds: {
      warning: 30,
      critical: 15,
      direction: 'below',
    },
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0, suffix: '%' },
  },
  {
    id: 'engagement.pages_per_session',
    name: 'Pages per Session',
    description: 'Average number of pages viewed per session',
    category: 'engagement',
    type: 'gauge',
    unit: 'pages',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system'],
    thresholds: {
      warning: 1.5,
      critical: 1.1,
      direction: 'below',
    },
    source: 'calculated',
    dashboards: ['pm'],
    format: { decimals: 1 },
  },
  {
    id: 'engagement.return_visitor_rate',
    name: 'Return Visitor Rate',
    description: 'Percentage of visitors who return',
    category: 'engagement',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['week', 'month'],
    entityTypes: ['system'],
    source: 'calculated',
    dashboards: ['pm'],
    format: { decimals: 1, suffix: '%' },
  },
];

// =====================================================
// TRAFFIC METRICS
// =====================================================

export const TRAFFIC_METRICS: MetricDefinition[] = [
  {
    id: 'traffic.total_sessions',
    name: 'Total Sessions',
    description: 'Total number of user sessions',
    category: 'traffic',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['realtime', 'hour', 'day', 'week', 'month'],
    entityTypes: ['system'],
    source: 'database',
    dashboards: ['all'],
    format: { decimals: 0 },
  },
  {
    id: 'traffic.organic_sessions',
    name: 'Organic Sessions',
    description: 'Sessions from organic search',
    category: 'traffic',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'channel'],
    source: 'database',
    dashboards: ['seo'],
    format: { decimals: 0 },
  },
  {
    id: 'traffic.ai_referral_sessions',
    name: 'AI Referral Sessions',
    description: 'Sessions from AI platforms (ChatGPT, Perplexity, etc.)',
    category: 'traffic',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'platform'],
    source: 'database',
    dashboards: ['seo', 'pm'],
    format: { decimals: 0 },
  },
  {
    id: 'traffic.direct_sessions',
    name: 'Direct Sessions',
    description: 'Sessions from direct traffic',
    category: 'traffic',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system'],
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0 },
  },
  {
    id: 'traffic.referral_sessions',
    name: 'Referral Sessions',
    description: 'Sessions from external referrals',
    category: 'traffic',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'channel'],
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0 },
  },
  {
    id: 'traffic.social_sessions',
    name: 'Social Sessions',
    description: 'Sessions from social media',
    category: 'traffic',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'platform'],
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0 },
  },
  {
    id: 'traffic.new_vs_returning',
    name: 'New vs Returning Ratio',
    description: 'Ratio of new visitors to returning visitors',
    category: 'traffic',
    type: 'rate',
    unit: 'ratio',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system'],
    source: 'calculated',
    dashboards: ['pm'],
    format: { decimals: 2 },
  },
];

// =====================================================
// SEO METRICS
// =====================================================

export const SEO_METRICS: MetricDefinition[] = [
  {
    id: 'seo.impressions',
    name: 'Search Impressions',
    description: 'Total search impressions from Google',
    category: 'seo',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'destination', 'system'],
    source: 'external',
    dashboards: ['seo'],
    format: { decimals: 0 },
  },
  {
    id: 'seo.clicks',
    name: 'Search Clicks',
    description: 'Total clicks from search results',
    category: 'seo',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'destination', 'system'],
    source: 'external',
    dashboards: ['seo'],
    format: { decimals: 0 },
  },
  {
    id: 'seo.ctr',
    name: 'Click-Through Rate',
    description: 'Percentage of impressions that result in clicks',
    category: 'seo',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'destination', 'system'],
    thresholds: {
      warning: 2,
      critical: 1,
      direction: 'below',
    },
    source: 'calculated',
    dashboards: ['seo'],
    format: { decimals: 2, suffix: '%' },
    formula: '(clicks / impressions) * 100',
    dependsOn: ['seo.clicks', 'seo.impressions'],
  },
  {
    id: 'seo.average_position',
    name: 'Average Search Position',
    description: 'Average position in search results',
    category: 'seo',
    type: 'gauge',
    unit: 'position',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'destination', 'system'],
    thresholds: {
      warning: 20,
      critical: 50,
      direction: 'above',
    },
    source: 'external',
    dashboards: ['seo'],
    format: { decimals: 1 },
  },
  {
    id: 'seo.indexed_pages',
    name: 'Indexed Pages',
    description: 'Number of pages indexed by Google',
    category: 'seo',
    type: 'gauge',
    unit: 'pages',
    aggregation: 'last',
    granularity: ['day', 'week'],
    entityTypes: ['system'],
    source: 'external',
    dashboards: ['seo', 'ops'],
    format: { decimals: 0 },
  },
  {
    id: 'seo.seo_score',
    name: 'SEO Score',
    description: 'Overall SEO optimization score',
    category: 'seo',
    type: 'score',
    unit: 'score',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    thresholds: {
      warning: 60,
      critical: 40,
      direction: 'below',
    },
    source: 'calculated',
    dashboards: ['seo'],
    format: { decimals: 0, suffix: '/100' },
  },
  {
    id: 'seo.keyword_rankings',
    name: 'Keyword Rankings',
    description: 'Number of keywords ranking in top positions',
    category: 'seo',
    type: 'gauge',
    unit: 'keywords',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    source: 'external',
    dashboards: ['seo'],
    format: { decimals: 0 },
  },
];

// =====================================================
// AEO METRICS (Answer Engine Optimization)
// =====================================================

export const AEO_METRICS: MetricDefinition[] = [
  {
    id: 'aeo.ai_impressions',
    name: 'AI Impressions',
    description: 'Estimated appearances in AI responses',
    category: 'aeo',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'platform', 'system'],
    source: 'database',
    dashboards: ['seo', 'pm'],
    format: { decimals: 0 },
  },
  {
    id: 'aeo.citations',
    name: 'AI Citations',
    description: 'Confirmed citations in AI responses',
    category: 'aeo',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'platform', 'system'],
    source: 'database',
    dashboards: ['seo', 'pm'],
    format: { decimals: 0 },
  },
  {
    id: 'aeo.citation_rate',
    name: 'Citation Rate',
    description: 'Percentage of impressions resulting in citations',
    category: 'aeo',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    thresholds: {
      warning: 5,
      critical: 2,
      direction: 'below',
    },
    source: 'calculated',
    dashboards: ['seo'],
    format: { decimals: 1, suffix: '%' },
    formula: '(citations / ai_impressions) * 100',
    dependsOn: ['aeo.citations', 'aeo.ai_impressions'],
  },
  {
    id: 'aeo.click_throughs',
    name: 'AI Click-Throughs',
    description: 'Clicks from AI platforms to our site',
    category: 'aeo',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'platform', 'system'],
    source: 'database',
    dashboards: ['seo', 'pm'],
    format: { decimals: 0 },
  },
  {
    id: 'aeo.avg_position',
    name: 'AI Response Position',
    description: 'Average position in AI responses',
    category: 'aeo',
    type: 'gauge',
    unit: 'position',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'platform', 'system'],
    thresholds: {
      warning: 3,
      critical: 5,
      direction: 'above',
    },
    source: 'database',
    dashboards: ['seo'],
    format: { decimals: 1 },
  },
  {
    id: 'aeo.aeo_score',
    name: 'AEO Score',
    description: 'Answer Engine Optimization score',
    category: 'aeo',
    type: 'score',
    unit: 'score',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    thresholds: {
      warning: 60,
      critical: 40,
      direction: 'below',
    },
    source: 'database',
    dashboards: ['seo'],
    format: { decimals: 0, suffix: '/100' },
  },
  {
    id: 'aeo.crawler_visits',
    name: 'AI Crawler Visits',
    description: 'Visits from AI platform crawlers',
    category: 'aeo',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'platform', 'system'],
    source: 'database',
    dashboards: ['seo', 'ops'],
    format: { decimals: 0 },
  },
];

// =====================================================
// CONTENT METRICS
// =====================================================

export const CONTENT_METRICS: MetricDefinition[] = [
  {
    id: 'content.total_published',
    name: 'Published Content',
    description: 'Total number of published content pieces',
    category: 'content',
    type: 'gauge',
    unit: 'pieces',
    aggregation: 'count',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system'],
    source: 'database',
    dashboards: ['pm', 'ops'],
    format: { decimals: 0 },
  },
  {
    id: 'content.created_this_period',
    name: 'Content Created',
    description: 'Content pieces created in period',
    category: 'content',
    type: 'counter',
    unit: 'pieces',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'writer'],
    source: 'database',
    dashboards: ['pm', 'ops'],
    format: { decimals: 0 },
  },
  {
    id: 'content.avg_word_count',
    name: 'Average Word Count',
    description: 'Average word count of content',
    category: 'content',
    type: 'gauge',
    unit: 'words',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0 },
  },
  {
    id: 'content.performance_score',
    name: 'Content Performance Score',
    description: 'Unified content performance score',
    category: 'content',
    type: 'score',
    unit: 'score',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    thresholds: {
      warning: 50,
      critical: 30,
      direction: 'below',
    },
    source: 'calculated',
    dashboards: ['pm', 'seo'],
    format: { decimals: 0, suffix: '/100' },
  },
  {
    id: 'content.freshness_score',
    name: 'Content Freshness Score',
    description: 'How recently content has been updated',
    category: 'content',
    type: 'score',
    unit: 'score',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    thresholds: {
      warning: 50,
      critical: 30,
      direction: 'below',
    },
    source: 'calculated',
    dashboards: ['pm', 'seo'],
    format: { decimals: 0, suffix: '/100' },
  },
  {
    id: 'content.quality_score',
    name: 'Content Quality Score',
    description: 'AI-evaluated content quality',
    category: 'content',
    type: 'score',
    unit: 'score',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'writer', 'system'],
    thresholds: {
      warning: 60,
      critical: 40,
      direction: 'below',
    },
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0, suffix: '/100' },
  },
  {
    id: 'content.decay_rate',
    name: 'Content Decay Rate',
    description: 'Rate at which content loses engagement',
    category: 'content',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['week', 'month'],
    entityTypes: ['content', 'system'],
    thresholds: {
      warning: 20,
      critical: 40,
      direction: 'above',
    },
    source: 'calculated',
    dashboards: ['seo', 'pm'],
    format: { decimals: 1, suffix: '%' },
  },
];

// =====================================================
// CONVERSION METRICS
// =====================================================

export const CONVERSION_METRICS: MetricDefinition[] = [
  {
    id: 'conversion.total_conversions',
    name: 'Total Conversions',
    description: 'Total number of conversions',
    category: 'conversion',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['hour', 'day', 'week', 'month'],
    entityTypes: ['system', 'campaign', 'channel'],
    source: 'database',
    dashboards: ['pm', 'ops'],
    format: { decimals: 0 },
  },
  {
    id: 'conversion.conversion_rate',
    name: 'Conversion Rate',
    description: 'Percentage of visitors who convert',
    category: 'conversion',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'channel', 'content'],
    thresholds: {
      warning: 1,
      critical: 0.5,
      direction: 'below',
    },
    source: 'calculated',
    dashboards: ['pm'],
    format: { decimals: 2, suffix: '%' },
    formula: '(conversions / sessions) * 100',
  },
  {
    id: 'conversion.newsletter_signups',
    name: 'Newsletter Signups',
    description: 'New newsletter subscriptions',
    category: 'conversion',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'campaign'],
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0 },
  },
  {
    id: 'conversion.lead_form_submissions',
    name: 'Lead Form Submissions',
    description: 'Contact or lead form submissions',
    category: 'conversion',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'content'],
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0 },
  },
  {
    id: 'conversion.affiliate_clicks',
    name: 'Affiliate Clicks',
    description: 'Clicks on affiliate links',
    category: 'conversion',
    type: 'counter',
    unit: 'count',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['content', 'system'],
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0 },
  },
  {
    id: 'conversion.funnel_completion_rate',
    name: 'Funnel Completion Rate',
    description: 'Percentage completing full funnel',
    category: 'conversion',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system'],
    thresholds: {
      warning: 10,
      critical: 5,
      direction: 'below',
    },
    source: 'calculated',
    dashboards: ['pm'],
    format: { decimals: 2, suffix: '%' },
  },
];

// =====================================================
// REVENUE METRICS
// =====================================================

export const REVENUE_METRICS: MetricDefinition[] = [
  {
    id: 'revenue.total_revenue',
    name: 'Total Revenue',
    description: 'Total revenue in cents',
    category: 'revenue',
    type: 'currency',
    unit: 'cents',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'channel', 'campaign'],
    source: 'database',
    dashboards: ['pm', 'ops'],
    format: { decimals: 0, prefix: '$', suffix: '' },
  },
  {
    id: 'revenue.affiliate_revenue',
    name: 'Affiliate Revenue',
    description: 'Revenue from affiliate programs',
    category: 'revenue',
    type: 'currency',
    unit: 'cents',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'content'],
    source: 'database',
    dashboards: ['pm'],
    format: { decimals: 0, prefix: '$' },
  },
  {
    id: 'revenue.revenue_per_session',
    name: 'Revenue per Session',
    description: 'Average revenue per session in cents',
    category: 'revenue',
    type: 'currency',
    unit: 'cents',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'channel'],
    source: 'calculated',
    dashboards: ['pm'],
    format: { decimals: 2, prefix: '$' },
    formula: 'total_revenue / total_sessions',
  },
  {
    id: 'revenue.revenue_per_content',
    name: 'Revenue per Content',
    description: 'Average revenue per content piece',
    category: 'revenue',
    type: 'currency',
    unit: 'cents',
    aggregation: 'avg',
    granularity: ['week', 'month'],
    entityTypes: ['content', 'system'],
    source: 'calculated',
    dashboards: ['pm'],
    format: { decimals: 2, prefix: '$' },
  },
];

// =====================================================
// COST METRICS
// =====================================================

export const COST_METRICS: MetricDefinition[] = [
  {
    id: 'cost.ai_api_cost',
    name: 'AI API Cost',
    description: 'Cost of AI API usage in cents',
    category: 'cost',
    type: 'currency',
    unit: 'cents',
    aggregation: 'sum',
    granularity: ['hour', 'day', 'week', 'month'],
    entityTypes: ['system'],
    thresholds: {
      warning: 100000, // $1000
      critical: 500000, // $5000
      direction: 'above',
    },
    source: 'database',
    dashboards: ['ops'],
    format: { decimals: 0, prefix: '$' },
  },
  {
    id: 'cost.content_generation_cost',
    name: 'Content Generation Cost',
    description: 'Cost of AI content generation',
    category: 'cost',
    type: 'currency',
    unit: 'cents',
    aggregation: 'sum',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'writer'],
    source: 'database',
    dashboards: ['ops', 'pm'],
    format: { decimals: 0, prefix: '$' },
  },
  {
    id: 'cost.cost_per_content',
    name: 'Cost per Content',
    description: 'Average cost per content piece created',
    category: 'cost',
    type: 'currency',
    unit: 'cents',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system', 'writer'],
    source: 'calculated',
    dashboards: ['ops'],
    format: { decimals: 2, prefix: '$' },
  },
  {
    id: 'cost.roi',
    name: 'ROI',
    description: 'Return on investment percentage',
    category: 'cost',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['week', 'month'],
    entityTypes: ['system', 'campaign'],
    source: 'calculated',
    dashboards: ['pm', 'ops'],
    format: { decimals: 1, suffix: '%' },
    formula: '((revenue - cost) / cost) * 100',
    dependsOn: ['revenue.total_revenue', 'cost.ai_api_cost'],
  },
];

// =====================================================
// GROWTH METRICS
// =====================================================

export const GROWTH_METRICS: MetricDefinition[] = [
  {
    id: 'growth.search_loop_conversion',
    name: 'Search Loop Conversion',
    description: 'Search to content discovery conversion rate',
    category: 'growth',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['hour', 'day', 'week'],
    entityTypes: ['system'],
    source: 'realtime',
    dashboards: ['pm', 'seo'],
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'growth.chat_loop_conversion',
    name: 'Chat Loop Conversion',
    description: 'Chat to exploration conversion rate',
    category: 'growth',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['hour', 'day', 'week'],
    entityTypes: ['system'],
    source: 'realtime',
    dashboards: ['pm'],
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'growth.content_loop_retention',
    name: 'Content Loop Retention',
    description: 'Content performance to retention rate',
    category: 'growth',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week'],
    entityTypes: ['system'],
    source: 'realtime',
    dashboards: ['pm'],
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'growth.internal_link_ctr',
    name: 'Internal Link CTR',
    description: 'Click-through rate on internal links',
    category: 'growth',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week'],
    entityTypes: ['content', 'system'],
    source: 'realtime',
    dashboards: ['seo'],
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'growth.content_freshness',
    name: 'Content Freshness Score',
    description: 'Overall content freshness score',
    category: 'growth',
    type: 'score',
    unit: 'score',
    aggregation: 'last',
    granularity: ['day', 'week'],
    entityTypes: ['system'],
    source: 'realtime',
    dashboards: ['pm', 'seo'],
    format: { decimals: 1, suffix: '/10' },
  },
];

// =====================================================
// HEALTH METRICS
// =====================================================

export const HEALTH_METRICS: MetricDefinition[] = [
  {
    id: 'health.api_response_time',
    name: 'API Response Time',
    description: 'Average API response time in milliseconds',
    category: 'health',
    type: 'duration',
    unit: 'ms',
    aggregation: 'avg',
    granularity: ['minute', 'hour', 'day'],
    entityTypes: ['system'],
    thresholds: {
      warning: 500,
      critical: 2000,
      direction: 'above',
    },
    source: 'realtime',
    dashboards: ['ops'],
    format: { decimals: 0, suffix: 'ms' },
  },
  {
    id: 'health.error_rate',
    name: 'Error Rate',
    description: 'Percentage of requests resulting in errors',
    category: 'health',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['minute', 'hour', 'day'],
    entityTypes: ['system'],
    thresholds: {
      warning: 1,
      critical: 5,
      direction: 'above',
    },
    source: 'realtime',
    dashboards: ['ops'],
    format: { decimals: 2, suffix: '%' },
  },
  {
    id: 'health.uptime',
    name: 'Uptime',
    description: 'System uptime percentage',
    category: 'health',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['day', 'week', 'month'],
    entityTypes: ['system'],
    thresholds: {
      warning: 99.5,
      critical: 99,
      direction: 'below',
    },
    source: 'realtime',
    dashboards: ['ops'],
    format: { decimals: 2, suffix: '%' },
  },
  {
    id: 'health.database_connections',
    name: 'Database Connections',
    description: 'Active database connections',
    category: 'health',
    type: 'gauge',
    unit: 'connections',
    aggregation: 'last',
    granularity: ['minute', 'hour'],
    entityTypes: ['system'],
    thresholds: {
      warning: 80,
      critical: 95,
      direction: 'above',
    },
    source: 'realtime',
    dashboards: ['ops'],
    format: { decimals: 0 },
  },
  {
    id: 'health.cache_hit_rate',
    name: 'Cache Hit Rate',
    description: 'Percentage of cache hits',
    category: 'health',
    type: 'rate',
    unit: '%',
    aggregation: 'avg',
    granularity: ['hour', 'day'],
    entityTypes: ['system'],
    thresholds: {
      warning: 80,
      critical: 60,
      direction: 'below',
    },
    source: 'realtime',
    dashboards: ['ops'],
    format: { decimals: 1, suffix: '%' },
  },
  {
    id: 'health.job_queue_length',
    name: 'Job Queue Length',
    description: 'Number of jobs in queue',
    category: 'health',
    type: 'gauge',
    unit: 'jobs',
    aggregation: 'last',
    granularity: ['minute', 'hour'],
    entityTypes: ['system'],
    thresholds: {
      warning: 100,
      critical: 500,
      direction: 'above',
    },
    source: 'realtime',
    dashboards: ['ops'],
    format: { decimals: 0 },
  },
];

// =====================================================
// COMBINED REGISTRY
// =====================================================

export const ALL_METRICS: MetricDefinition[] = [
  ...ENGAGEMENT_METRICS,
  ...TRAFFIC_METRICS,
  ...SEO_METRICS,
  ...AEO_METRICS,
  ...CONTENT_METRICS,
  ...CONVERSION_METRICS,
  ...REVENUE_METRICS,
  ...COST_METRICS,
  ...GROWTH_METRICS,
  ...HEALTH_METRICS,
];

// Create a lookup map for fast access
export const METRICS_MAP: Map<string, MetricDefinition> = new Map(
  ALL_METRICS.map(m => [m.id, m])
);

// Helper to get metric by ID
export function getMetricDefinition(id: string): MetricDefinition | undefined {
  return METRICS_MAP.get(id);
}

// Helper to get metrics by category
export function getMetricsByCategory(category: string): MetricDefinition[] {
  return ALL_METRICS.filter(m => m.category === category);
}

// Helper to get metrics for a dashboard
export function getMetricsForDashboard(role: 'pm' | 'seo' | 'ops'): MetricDefinition[] {
  return ALL_METRICS.filter(m => m.dashboards.includes(role) || m.dashboards.includes('all'));
}
