import { db } from "../server/db";
import { topicBank } from "../shared/schema";

// 200+ Dubai Viral Topics Bank
const viralTopics = [
  // ===== LUXURY & LIFESTYLE (25 Topics) =====
  { title: "$100,000/Night Atlantis Royal Suite", headlineAngle: "Inside the Suite Where Beyoncé Stayed", viralPotential: "5" as const, format: "video_tour" as const, topicType: "trending" as const, mainCategory: "luxury_lifestyle" as const, category: "hotels" as const, keywords: ["Dubai luxury", "Atlantis suite", "most expensive Dubai hotel"] },
  { title: "Burj Al Arab Presidential Suite", headlineAngle: "What $32,700/Night Gets You at the 'Only 7-Star Hotel'", viralPotential: "5" as const, format: "photo_gallery" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "hotels" as const, keywords: ["Burj Al Arab suite", "Dubai billionaire lifestyle"] },
  { title: "AURA Skypool World's Highest Pool", headlineAngle: "Swimming 210 Meters Above Dubai", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "attractions" as const, keywords: ["AURA Skypool Dubai", "highest pool world"] },
  { title: "Private Yacht Charter Experience", headlineAngle: "How Much Does a Private Yacht Cost in Dubai?", viralPotential: "4" as const, format: "cost_breakdown" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "attractions" as const, keywords: ["Dubai yacht rental", "private yacht Dubai cost"] },
  { title: "Chauffeur-Driven Rolls-Royce Tours", headlineAngle: "Experiencing Dubai Like Royalty", viralPotential: "3" as const, format: "lifestyle_vlog" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "transport" as const, keywords: ["Rolls Royce Dubai", "luxury car Dubai"] },
  { title: "Five-Star Pet Hotels", headlineAngle: "Dubai's Pet Hotels Have Pools and Chauffeurs", viralPotential: "4" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "tips" as const, keywords: ["Dubai pet hotel", "luxury pet care Dubai"] },
  { title: "Cloud 22 Moonlight Swimming", headlineAngle: "Night Swimming at Dubai's Most Exclusive Rooftop", viralPotential: "4" as const, format: "night_photography" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "attractions" as const, keywords: ["Cloud 22 Dubai", "rooftop pool Dubai"] },
  { title: "Helicopter Tours Over The Palm", headlineAngle: "12 Minutes Changed How I See Dubai", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "attractions" as const, keywords: ["Dubai helicopter tour", "Palm Jumeirah aerial"] },
  { title: "Supercar Spotting Sheikh Zayed Road", headlineAngle: "My Neighbor's Car Collection in Dubai POV", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "tips" as const, keywords: ["Dubai supercars", "Sheikh Zayed Road cars"] },
  { title: "Dubai Police Supercar Fleet", headlineAngle: "Dubai Police Drive $400K Lamborghinis", viralPotential: "5" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "tips" as const, keywords: ["Dubai police cars", "Lamborghini police Dubai"] },
  { title: "Renting a Lamborghini for a Day", headlineAngle: "What It Costs to Drive a Supercar in Dubai", viralPotential: "5" as const, format: "cost_breakdown" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "transport" as const, keywords: ["rent Lamborghini Dubai", "supercar rental Dubai cost"] },
  { title: "What Do You Do for a Living?", headlineAngle: "Street interviews with supercar owners", viralPotential: "5" as const, format: "interview" as const, topicType: "trending" as const, mainCategory: "luxury_lifestyle" as const, category: "tips" as const, keywords: ["Dubai rich lifestyle", "what do you do Dubai"] },
  { title: "Abandoned Supercars Investigation", headlineAngle: "3,000 Ferraris Left to Rot in Dubai", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "news" as const, keywords: ["abandoned cars Dubai", "Ferrari graveyard Dubai"] },
  { title: "$18 Million License Plates", headlineAngle: "Single-Digit Plates Cost More Than Mansions", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "tips" as const, keywords: ["Dubai license plate cost", "most expensive plate Dubai"] },
  { title: "Gold ATMs", headlineAngle: "The ATM That Dispenses Gold Bars", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "shopping" as const, keywords: ["gold ATM Dubai", "buy gold Dubai"] },
  { title: "Gold Souk Experience", headlineAngle: "The World's Largest Gold Market Has a 63kg Ring", viralPotential: "4" as const, format: "walking_tour" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "shopping" as const, keywords: ["Gold Souk Dubai", "Dubai gold market"] },
  { title: "Dubai Mall Complete Guide", headlineAngle: "1,200 Shops, Olympic Rink, 33,000 Fish", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "shopping" as const, keywords: ["Dubai Mall guide", "biggest mall Dubai"] },
  { title: "Tax-Free Shopping Reality", headlineAngle: "What's Actually Worth Buying in Dubai", viralPotential: "4" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "luxury_lifestyle" as const, category: "shopping" as const, keywords: ["tax free Dubai", "what to buy Dubai"] },

  // ===== FOOD & DINING (30 Topics) =====
  { title: "Ossiano Underwater Restaurant", headlineAngle: "Eating Dinner While Sharks Swim Past", viralPotential: "5" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Ossiano Dubai", "underwater restaurant Dubai"] },
  { title: "Al Mahara Burj Al Arab", headlineAngle: "Fine Dining Inside a Submarine", viralPotential: "5" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Al Mahara Dubai", "Burj Al Arab restaurant"] },
  { title: "At.mosphere World's Highest Restaurant", headlineAngle: "Dinner on the 122nd Floor of Burj Khalifa", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["At.mosphere Dubai", "Burj Khalifa restaurant"] },
  { title: "Sublimotion $5,000 Dinner Show", headlineAngle: "The 12-Seat Restaurant That Changes Reality", viralPotential: "5" as const, format: "video_tour" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Sublimotion Dubai", "most expensive dinner Dubai"] },
  { title: "KRASOTA Gastro-Theatre", headlineAngle: "Eating Inside a 3D Art Installation", viralPotential: "5" as const, format: "video_tour" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["KRASOTA Dubai", "immersive dining Dubai"] },
  { title: "Dinner in the Sky", headlineAngle: "This Restaurant Dangles 165 Feet in the Air", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Dinner in the Sky Dubai", "sky dining Dubai"] },
  { title: "Pierchic Ocean Pier Dining", headlineAngle: "The Restaurant Built on a Pier Into the Sea", viralPotential: "4" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Pierchic Dubai", "seafood restaurant Dubai"] },
  { title: "Salt Bae's Golden Steak", headlineAngle: "I Spent $275 on ONE Steak", viralPotential: "5" as const, format: "reaction_video" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Salt Bae Dubai", "Nusr-Et Dubai", "golden steak Dubai"] },
  { title: "Gordon Ramsay's Hell's Kitchen", headlineAngle: "The Beef Wellington That Made Gordon Famous", viralPotential: "5" as const, format: "review" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Hell's Kitchen Dubai", "Gordon Ramsay Dubai"] },
  { title: "CZN Burak Viral Chef", headlineAngle: "The Smiling Chef Who Broke the Internet", viralPotential: "5" as const, format: "food_tour" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["CZN Burak Dubai", "viral chef Dubai"] },
  { title: "FZN by Björn Frantzén", headlineAngle: "Dubai's Best Restaurant 2025 Experience", viralPotential: "4" as const, format: "review" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["FZN Dubai", "best restaurant Dubai 2025"] },
  { title: "Trèsind Studio 3-Michelin Star", headlineAngle: "World's Only 3-Michelin Star Indian", viralPotential: "5" as const, format: "review" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Trèsind Studio Dubai", "Michelin star Dubai"] },
  { title: "Orfali Bros MENA's Best", headlineAngle: "Syrian Brothers Made MENA's #1 Restaurant", viralPotential: "4" as const, format: "interview" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Orfali Bros Dubai", "best restaurant MENA"] },
  { title: "Dubai Chocolate ASMR", headlineAngle: "The Fix Dessert Chocolatier That Got 139M Views", viralPotential: "5" as const, format: "asmr" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Dubai chocolate viral", "Fix Dessert Chocolatier"] },
  { title: "DIY Dubai Chocolate", headlineAngle: "Making the Viral Dubai Chocolate at Home", viralPotential: "5" as const, format: "tutorial" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Dubai chocolate recipe", "viral chocolate recipe"] },
  { title: "Gold-Covered Food Tour", headlineAngle: "Everything Covered in Gold I Could Find", viralPotential: "5" as const, format: "food_tour" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["gold food Dubai", "24k gold food"] },
  { title: "$1,000 Gold Biryani", headlineAngle: "23-Karat Gold on Rice at Bombay Borough", viralPotential: "5" as const, format: "reaction_video" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["gold biryani Dubai", "expensive biryani Dubai"] },
  { title: "Fire Pani Puri", headlineAngle: "They Set My Food on Fire", viralPotential: "5" as const, format: "reaction_video" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["fire pani puri Dubai", "viral food Dubai"] },
  { title: "NAV-AT Teddy Bear Café", headlineAngle: "The Restaurant Where Your Date is a Teddy Bear", viralPotential: "5" as const, format: "video_tour" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["NAV-AT Dubai", "teddy bear café Dubai"] },
  { title: "T-Rex Adventure Café", headlineAngle: "Dining with Dinosaurs in Dubai", viralPotential: "5" as const, format: "video_tour" as const, topicType: "trending" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["T-Rex café Dubai", "dinosaur restaurant Dubai"] },
  { title: "Best Street Food Old Dubai", headlineAngle: "The Food Tourists Never Try", viralPotential: "5" as const, format: "food_tour" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["street food Dubai", "Old Dubai food"] },
  { title: "How Locals Eat Cheap", headlineAngle: "Ethiopian, Indian, Pakistani Budget Eats", viralPotential: "5" as const, format: "food_tour" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["cheap food Dubai", "budget eats Dubai"] },
  { title: "Traditional Emirati Cuisine", headlineAngle: "Machboos, Harees, Luqaimat: The Real UAE", viralPotential: "4" as const, format: "food_tour" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Emirati food", "traditional Dubai food"] },
  { title: "$3 Shawarma vs $300 Steak", headlineAngle: "Budget vs Luxury Dubai Food Challenge", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["cheap vs expensive Dubai", "Dubai food challenge"] },
  { title: "Dubai Brunch Culture", headlineAngle: "Is $150 Unlimited Brunch Worth It?", viralPotential: "5" as const, format: "review" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Dubai brunch", "Friday brunch Dubai"] },
  { title: "Aesthetic Pink Cafés", headlineAngle: "EL&N, Tania's Teahouse, Saya Brasserie", viralPotential: "4" as const, format: "photo_gallery" as const, topicType: "evergreen" as const, mainCategory: "food_dining" as const, category: "food" as const, keywords: ["Instagram cafés Dubai", "pink café Dubai"] },

  // ===== BIZARRE & UNIQUE (25 Topics) =====
  { title: "The Middle Finger Fine", headlineAngle: "The $3,000 Hand Gesture That Gets You Deported", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai laws tourists", "illegal gestures Dubai"] },
  { title: "The Gossip Law", headlineAngle: "Dubai's $270,000 Fine for Spreading Rumors", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai gossip law", "weird Dubai laws"] },
  { title: "The Phone Privacy Law", headlineAngle: "Checking Your Partner's Phone = Jail", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai phone privacy law", "Dubai jail laws"] },
  { title: "The Photo Crime Law", headlineAngle: "Taking This Photo Could Cost You $800,000", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai photography laws", "illegal photos Dubai"] },
  { title: "The VPN Crime", headlineAngle: "Using a VPN Could Cost You $500,000", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["VPN Dubai illegal", "Dubai VPN fine"] },
  { title: "The Dirty Car Fine", headlineAngle: "Dubai Will Tow Your Car for Being Too Dusty", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["dirty car Dubai", "Dubai car laws"] },
  { title: "The Dancing Ban", headlineAngle: "You Can't Dance on the Street in Dubai", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai dancing law", "public dancing Dubai"] },
  { title: "The Poppy Seed Ban", headlineAngle: "Tourists Jailed for Poppy Seeds on Bagels", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["poppy seeds Dubai", "banned items Dubai"] },
  { title: "The Negative Review Law", headlineAngle: "Tourists Get Banned for Bad Google Reviews", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai review law", "defamation Dubai"] },
  { title: "Robot Camel Jockeys", headlineAngle: "Dubai Replaced Child Jockeys with Robots", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "attractions" as const, keywords: ["robot camel jockey", "camel racing Dubai"] },
  { title: "Indoor Skiing in the Desert", headlineAngle: "There's a Ski Slope in a Shopping Mall", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "attractions" as const, keywords: ["Ski Dubai", "indoor skiing Dubai"] },
  { title: "Pet Lions & Tigers", headlineAngle: "Why You See Tigers in Car Windows", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["pet lion Dubai", "exotic pets Dubai"] },
  { title: "Helicopter Uber", headlineAngle: "You Can Order a Helicopter Like an Uber", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "transport" as const, keywords: ["helicopter taxi Dubai", "Uber helicopter Dubai"] },
  { title: "Rain in Dubai Goes Viral", headlineAngle: "When It Rains, the Whole City Stops", viralPotential: "5" as const, format: "documentary" as const, topicType: "trending" as const, mainCategory: "bizarre_unique" as const, category: "news" as const, keywords: ["Dubai rain", "rain in desert Dubai"] },
  { title: "The Left Hand Taboo", headlineAngle: "Why Using Your Left Hand Can Offend Everyone", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai etiquette", "left hand Dubai"] },
  { title: "The 91% Expat Shock", headlineAngle: "Only 9% of People Here Are Actually Emirati", viralPotential: "5" as const, format: "infographic" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai expat population", "Emiratis percentage"] },
  { title: "The Call to Prayer", headlineAngle: "The Sound You'll Hear 5 Times Daily", viralPotential: "4" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai call to prayer", "adhan Dubai"] },
  { title: "The Weekend Flip", headlineAngle: "Why Friday Feels Like Sunday in Dubai", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["Dubai weekend", "Friday Saturday Dubai"] },
  { title: "Things Normal Only in Dubai", headlineAngle: "Gold ATMs, Police Ferraris, Indoor Skiing", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "bizarre_unique" as const, category: "tips" as const, keywords: ["only in Dubai", "Dubai unique things"] },

  // ===== EXPERIENCES & ACTIVITIES (30 Topics) =====
  { title: "Skydiving Over Palm Jumeirah", headlineAngle: "The World's Most Instagrammable Skydive", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["skydive Dubai", "Palm Jumeirah skydive"] },
  { title: "Jebel Jais World's Longest Zipline", headlineAngle: "Flying at 150km/h Across Mountains", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Jebel Jais zipline", "longest zipline world"] },
  { title: "Hot Air Balloon Over Desert", headlineAngle: "Sunrise 4,000ft Above Dubai's Desert", viralPotential: "5" as const, format: "drone_footage" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["hot air balloon Dubai", "Dubai desert balloon"] },
  { title: "Dune Buggy Racing", headlineAngle: "Racing Through Sand Dunes at Sunset", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["dune buggy Dubai", "desert racing Dubai"] },
  { title: "Jet Ski Around Palm Jumeirah", headlineAngle: "POV Jet Ski With Burj Al Arab Views", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["jet ski Dubai", "Palm Jumeirah jet ski"] },
  { title: "Deep Dive Dubai (60m Pool)", headlineAngle: "The World's Deepest Pool Has a Sunken City", viralPotential: "5" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Deep Dive Dubai", "deepest pool world"] },
  { title: "Al Qudra Love Lakes", headlineAngle: "Heart-Shaped Lakes Tourists Don't Know", viralPotential: "5" as const, format: "drone_footage" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Love Lakes Dubai", "Al Qudra Lakes"] },
  { title: "Black Palace Beach", headlineAngle: "Dubai's Hidden Beach Behind Burj Al Arab", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Black Palace Beach Dubai", "hidden beach Dubai"] },
  { title: "Ras Al Khor Flamingos", headlineAngle: "Wild Flamingos Minutes From Downtown", viralPotential: "4" as const, format: "drone_footage" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Dubai flamingos", "Ras Al Khor wildlife"] },
  { title: "Alserkal Avenue Art District", headlineAngle: "Dubai's Coolest Neighborhood Tourists Miss", viralPotential: "4" as const, format: "walking_tour" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Alserkal Avenue Dubai", "Dubai art district"] },
  { title: "Moon Island Camping", headlineAngle: "The Private Island You Can Visit", viralPotential: "5" as const, format: "lifestyle_vlog" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Moon Island Dubai", "camping Dubai island"] },
  { title: "Hatta Mountain Kayaking", headlineAngle: "The Day Trip Nobody Talks About", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Hatta kayak", "Hatta day trip"] },
  { title: "Fossil Dunes Al Wathba", headlineAngle: "The Alien Landscape Near Dubai", viralPotential: "4" as const, format: "photo_gallery" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Fossil Dunes UAE", "Al Wathba Dubai"] },
  { title: "VIP Desert Glamping", headlineAngle: "Sleeping in a $2,000/Night Desert Tent", viralPotential: "5" as const, format: "lifestyle_vlog" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Dubai glamping", "luxury desert camp Dubai"] },
  { title: "Desert Safari Comparison", headlineAngle: "Billionaire Safari vs Tourist Safari", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Dubai desert safari", "best safari Dubai"] },
  { title: "Desert Conservation Reserve", headlineAngle: "Ethical Safari with Arabian Oryx", viralPotential: "4" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Dubai Conservation Reserve", "Arabian Oryx Dubai"] },
  { title: "Overnight Desert Camp", headlineAngle: "Stargazing in the Arabian Desert", viralPotential: "4" as const, format: "lifestyle_vlog" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["overnight desert Dubai", "desert camping Dubai"] },
  { title: "Dune Bashing POV", headlineAngle: "60 Seconds of Desert Adrenaline", viralPotential: "5" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["dune bashing Dubai", "desert driving Dubai"] },
  { title: "Dubai Frame", headlineAngle: "Old vs New Dubai in One Photo", viralPotential: "5" as const, format: "photo_gallery" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Dubai Frame", "Dubai Frame view"] },
  { title: "Museum of the Future", headlineAngle: "Inside the World's Most Beautiful Building", viralPotential: "5" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Museum of the Future Dubai", "MOTF Dubai"] },
  { title: "The View at Palm Tower", headlineAngle: "Cheaper Burj Khalifa Alternative", viralPotential: "4" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["The View Palm Tower", "Palm Tower observation"] },
  { title: "Al Fahidi Historic District", headlineAngle: "The Original Dubai Before Skyscrapers", viralPotential: "4" as const, format: "walking_tour" as const, topicType: "evergreen" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Al Fahidi Dubai", "Old Dubai tour"] },
  { title: "Dubai Miracle Garden", headlineAngle: "150 Million Flowers in the Desert", viralPotential: "5" as const, format: "drone_footage" as const, topicType: "seasonal" as const, mainCategory: "experiences_activities" as const, category: "attractions" as const, keywords: ["Dubai Miracle Garden", "flower garden Dubai"] },

  // ===== MONEY & COST (25 Topics) =====
  { title: "Is Dubai Actually Expensive?", headlineAngle: "Dubai Is 45% Cheaper Than NYC", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["is Dubai expensive", "Dubai cost of living"] },
  { title: "What $100 Gets You in Dubai", headlineAngle: "Visual Comparison of Your Dollar", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["$100 Dubai", "Dubai budget"] },
  { title: "What $500 Gets You: 3 Days", headlineAngle: "Dubai on a Real Budget Challenge", viralPotential: "5" as const, format: "challenge" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["Dubai budget travel", "cheap Dubai trip"] },
  { title: "Budget vs Luxury Same Experience", headlineAngle: "$30 Hotel vs $1,000 Burj Al Arab", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["budget Dubai", "luxury vs cheap Dubai"] },
  { title: "Daily Tourist Budget Breakdown", headlineAngle: "$70-122/Day: Where It Goes", viralPotential: "4" as const, format: "infographic" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["Dubai daily budget", "Dubai trip cost"] },
  { title: "Hidden Costs Nobody Warns You About", headlineAngle: "30% Alcohol Tax, Municipality Fees, More", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["Dubai hidden costs", "Dubai fees tourists"] },
  { title: "The Real Cost of Alcohol", headlineAngle: "Why Your Beer Costs $10+ in Dubai", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["alcohol price Dubai", "beer cost Dubai"] },
  { title: "Hotel Hidden Fees", headlineAngle: "Tourism Fees, Knowledge Fees, and More", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "hotels" as const, keywords: ["Dubai hotel fees", "hidden hotel charges Dubai"] },
  { title: "Dubai Brunch: Is $150 Worth It?", headlineAngle: "The Unlimited Drinks Reality", viralPotential: "5" as const, format: "review" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "food" as const, keywords: ["Dubai brunch worth it", "best brunch Dubai"] },
  { title: "How to Do Dubai on $70/Day", headlineAngle: "Proven Budget Breakdown", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["Dubai on budget", "cheap Dubai guide"] },
  { title: "Free Things to Do in Dubai", headlineAngle: "Save Hundreds With This List", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["free Dubai", "free activities Dubai"] },
  { title: "The Entertainer App Hack", headlineAngle: "2-for-1 Everything in Dubai", viralPotential: "4" as const, format: "tutorial" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["Entertainer app Dubai", "Dubai discounts"] },
  { title: "Summer Hotel Deals", headlineAngle: "50% Off When Nobody Visits", viralPotential: "4" as const, format: "guide" as const, topicType: "seasonal" as const, mainCategory: "money_cost" as const, category: "hotels" as const, keywords: ["Dubai summer deals", "cheap hotels Dubai summer"] },
  { title: "Dubai for Non-Millionaires", headlineAngle: "Regular People's Dubai Guide", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["Dubai for normal people", "affordable Dubai"] },
  { title: "Cheap Eats Local Spots", headlineAngle: "How Residents Actually Eat Cheap", viralPotential: "5" as const, format: "food_tour" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "food" as const, keywords: ["cheap restaurants Dubai", "local food Dubai"] },
  { title: "Transport Hacks", headlineAngle: "Abra for $0.27, Metro Day Pass Tricks", viralPotential: "4" as const, format: "tutorial" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "transport" as const, keywords: ["Dubai metro pass", "cheap transport Dubai"] },
  { title: "Family of 4 Real Costs", headlineAngle: "$244/Day Average Breakdown", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["Dubai family trip cost", "Dubai with kids cost"] },
  { title: "Theme Park Combo Strategies", headlineAngle: "How to Save on Park Tickets", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "attractions" as const, keywords: ["Dubai parks discount", "theme park Dubai deals"] },
  { title: "Dubai vs Vegas Cost Comparison", headlineAngle: "Which Party City Is Cheaper?", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "money_cost" as const, category: "tips" as const, keywords: ["Dubai vs Vegas", "Dubai Vegas comparison"] },

  // ===== EXPAT & LIVING (25 Topics) =====
  { title: "The Truth About Living Here (3+ Years)", headlineAngle: "What Social Media Never Shows", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["living in Dubai", "Dubai expat life"] },
  { title: "Why I Left Dubai After X Years", headlineAngle: "The Departure Narrative", viralPotential: "5" as const, format: "interview" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["leaving Dubai", "why leave Dubai"] },
  { title: "Things I Wish I Knew Before Moving", headlineAngle: "10 Revelations from an Expat", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["moving to Dubai", "Dubai expat tips"] },
  { title: "Pros and Cons (Brutally Honest)", headlineAngle: "The Balanced View Nobody Gives", viralPotential: "5" as const, format: "review" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai pros cons", "Dubai honest review"] },
  { title: "The Dubai Stone Weight Gain", headlineAngle: "Why Everyone Gains Weight Here", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai weight gain", "Dubai stone"] },
  { title: "What Salary Do You REALLY Need?", headlineAngle: "AED 18,000-30,000 Comfortable Single", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai salary needed", "salary Dubai expat"] },
  { title: "Dubai Rents Up 30% Salaries Flat", headlineAngle: "The Middle Class Squeeze", viralPotential: "5" as const, format: "explainer" as const, topicType: "trending" as const, mainCategory: "expat_living" as const, category: "news" as const, keywords: ["Dubai rent increase", "Dubai housing crisis"] },
  { title: "Dubai Housing Reality", headlineAngle: "Rent Paid 1-4 Cheques Upfront", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai rent cheques", "renting in Dubai"] },
  { title: "Best Neighborhoods for Expats", headlineAngle: "Marina vs JLT vs Jumeirah Ranked", viralPotential: "4" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["best areas Dubai expats", "where to live Dubai"] },
  { title: "The Golden Visa Explained", headlineAngle: "10-Year Residency: Is It Worth It?", viralPotential: "5" as const, format: "explainer" as const, topicType: "trending" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai Golden Visa", "UAE 10 year visa"] },
  { title: "Dubai Dating Scene", headlineAngle: "What Nobody Tells You About Dating", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["dating in Dubai", "Dubai dating apps"] },
  { title: "Dubai Nightlife Honest Guide", headlineAngle: "Dress Codes, Ladies Nights, Minimum Spend", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai nightlife", "Dubai clubs guide"] },
  { title: "Making Friends as an Expat", headlineAngle: "The Transient Population Challenge", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["making friends Dubai", "Dubai expat community"] },
  { title: "Friday Brunch Culture", headlineAngle: "How Dubai Socializes", viralPotential: "4" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "food" as const, keywords: ["Dubai Friday brunch", "brunch culture Dubai"] },
  { title: "Dubai Work Culture", headlineAngle: "What Expats Don't Expect", viralPotential: "4" as const, format: "interview" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["working in Dubai", "Dubai office culture"] },
  { title: "Starting a Business Here", headlineAngle: "Real Setup Costs: 15,000 AED+", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["start business Dubai", "Dubai business setup cost"] },
  { title: "Why Expats Are Leaving", headlineAngle: "And Why Others Are Staying", viralPotential: "5" as const, format: "interview" as const, topicType: "trending" as const, mainCategory: "expat_living" as const, category: "news" as const, keywords: ["expats leaving Dubai", "Dubai exodus"] },
  { title: "The Debt Trap Warning", headlineAngle: "Why Expats Go Broke in Dubai", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai debt trap", "broke in Dubai"] },
  { title: "Passport Privilege in Job Hunting", headlineAngle: "The Uncomfortable Truth", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "news" as const, keywords: ["Dubai salary by nationality", "Dubai job discrimination"] },
  { title: "Dubai for Women: Safety Reality", headlineAngle: "Safest I've Ever Felt Walking Alone", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai safe for women", "female solo Dubai"] },
  { title: "Dubai Schools Guide", headlineAngle: "What Expat Parents Need to Know", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "tips" as const, keywords: ["Dubai schools expats", "best schools Dubai"] },
  { title: "Living Car-Free Challenge", headlineAngle: "Is Dubai Metro Enough?", viralPotential: "4" as const, format: "challenge" as const, topicType: "evergreen" as const, mainCategory: "expat_living" as const, category: "transport" as const, keywords: ["Dubai without car", "Dubai metro lifestyle"] },

  // ===== DARK SIDE & CONTROVERSY (20 Topics) =====
  { title: "The Real Dubai Nobody Shows", headlineAngle: "Instagram vs Reality", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["real Dubai", "Dubai reality"] },
  { title: "90% of People Are NOT Rich", headlineAngle: "The Working Class Reality", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Dubai working class", "Dubai not rich"] },
  { title: "The $300/Month Construction Workers", headlineAngle: "Building Skyscrapers on 6.5% Average Salary", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Dubai construction workers", "Dubai labor conditions"] },
  { title: "The Kafala System Explained", headlineAngle: "Sponsorship That Traps Workers", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["kafala system UAE", "Dubai worker sponsorship"] },
  { title: "Why Workers Can't Leave", headlineAngle: "Passport Confiscation Reality", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Dubai passport confiscation", "workers trapped Dubai"] },
  { title: "The World Islands Sinking", headlineAngle: "$14 Billion Islands Eroding Into the Sea", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["World Islands Dubai sinking", "Dubai failed projects"] },
  { title: "Ghost Towers of Dubai Marina", headlineAngle: "Billions in Unfinished Skyscrapers", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Dubai ghost towers", "unfinished buildings Dubai"] },
  { title: "Nakheel Tower That Never Was", headlineAngle: "The 1,400m Tower Cancelled in 2009", viralPotential: "4" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Nakheel Tower", "cancelled Dubai projects"] },
  { title: "The $27 Billion Bawadi Disaster", headlineAngle: "The Hotel City Dubai Quietly Abandoned", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Bawadi Dubai", "abandoned Dubai projects"] },
  { title: "Jebel Ali Ghost Village", headlineAngle: "300 Villas Completely Abandoned", viralPotential: "5" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Jebel Ali ghost town", "abandoned villas Dubai"] },
  { title: "Palm Islands' Ecological Cost", headlineAngle: "What They Buried to Build Them", viralPotential: "4" as const, format: "infographic" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Palm Jumeirah environmental", "Dubai ecological damage"] },
  { title: "The Beach Erosion Crisis", headlineAngle: "Losing 15,000 Cubic Meters of Sand Annually", viralPotential: "4" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Dubai beach erosion", "JBR sand problem"] },
  { title: "The AC Capital of the World", headlineAngle: "More Energy on Cooling Than Countries Use Total", viralPotential: "5" as const, format: "infographic" as const, topicType: "evergreen" as const, mainCategory: "dark_side" as const, category: "news" as const, keywords: ["Dubai AC consumption", "Dubai energy use"] },

  // ===== MYTH-BUSTING (15 Topics) =====
  { title: "The Dry Country Myth", headlineAngle: "Dubai Is NOT Dry – Here's Where to Drink", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "myth_busting" as const, category: "tips" as const, keywords: ["alcohol Dubai", "can you drink Dubai"] },
  { title: "The 7-Star Hotel Myth", headlineAngle: "Burj Al Arab Is Officially 5 Stars", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "myth_busting" as const, category: "hotels" as const, keywords: ["Burj Al Arab stars", "7 star hotel myth"] },
  { title: "The Always Covered Dress Myth", headlineAngle: "You Don't Need to Wear an Abaya", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "myth_busting" as const, category: "tips" as const, keywords: ["dress code Dubai women", "what to wear Dubai"] },
  { title: "The Women Can't Drive Myth", headlineAngle: "You're Thinking of Saudi Arabia", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "myth_busting" as const, category: "tips" as const, keywords: ["women driving Dubai", "Dubai vs Saudi Arabia"] },
  { title: "The No History Myth", headlineAngle: "Dubai Has Been Inhabited Since 2500 BC", viralPotential: "4" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "myth_busting" as const, category: "tips" as const, keywords: ["Dubai history", "old Dubai"] },
  { title: "The Everyone Rich Myth", headlineAngle: "Most Expats Are Working Class", viralPotential: "5" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "myth_busting" as const, category: "tips" as const, keywords: ["Dubai rich myth", "average salary Dubai"] },
  { title: "Dubai Is Dangerous Myth", headlineAngle: "One of the Safest Cities in the World", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "myth_busting" as const, category: "tips" as const, keywords: ["is Dubai safe", "Dubai crime rate"] },
  { title: "You Need Arabic Myth", headlineAngle: "English Works Almost Everywhere", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "myth_busting" as const, category: "tips" as const, keywords: ["Arabic needed Dubai", "English in Dubai"] },

  // ===== COMPARISONS (15 Topics) =====
  { title: "Dubai vs Singapore", headlineAngle: "Which Ultramodern City Should You Visit?", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Dubai vs Singapore", "Singapore or Dubai"] },
  { title: "Dubai vs Abu Dhabi", headlineAngle: "Same Country, Totally Different Vibes", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Dubai vs Abu Dhabi", "Abu Dhabi or Dubai"] },
  { title: "Dubai vs Las Vegas", headlineAngle: "Desert Cities Face Off", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Dubai vs Vegas", "Las Vegas or Dubai"] },
  { title: "Dubai vs Qatar/Doha", headlineAngle: "The Gulf Rivalry Explained", viralPotential: "4" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Dubai vs Doha", "Qatar or Dubai"] },
  { title: "Old Dubai vs New Dubai", headlineAngle: "Fishing Village to Futuristic City", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Old Dubai New Dubai", "Dubai transformation"] },
  { title: "Expectations vs Reality", headlineAngle: "What They Don't Tell You", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Dubai expectations reality", "Dubai honest guide"] },
  { title: "$100 Dubai vs $100 Singapore", headlineAngle: "Budget Challenge", viralPotential: "5" as const, format: "challenge" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Dubai vs Singapore cost", "budget travel comparison"] },
  { title: "Visiting vs Living", headlineAngle: "Two Different Worlds", viralPotential: "5" as const, format: "comparison" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["visiting Dubai vs living", "tourist vs expat Dubai"] },
  { title: "For Families vs Couples vs Solo", headlineAngle: "Which Type of Traveler?", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Dubai for families", "Dubai solo travel"] },
  { title: "First Time Dubai Skip These", headlineAngle: "Tourist Traps to Avoid", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "comparisons" as const, category: "tips" as const, keywords: ["Dubai tourist traps", "avoid Dubai mistakes"] },

  // ===== RECORDS & SUPERLATIVES (15 Topics) =====
  { title: "Dubai's 425+ World Records", headlineAngle: "The Most Insane Guinness Records", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "records_superlatives" as const, category: "attractions" as const, keywords: ["Dubai world records", "Guinness Dubai"] },
  { title: "Burj Khalifa's 6 Records", headlineAngle: "One Building, Six World Records", viralPotential: "5" as const, format: "infographic" as const, topicType: "evergreen" as const, mainCategory: "records_superlatives" as const, category: "attractions" as const, keywords: ["Burj Khalifa records", "tallest building world"] },
  { title: "Deep Dive Dubai 60m Pool", headlineAngle: "That's 11 Giraffes Stacked", viralPotential: "5" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "records_superlatives" as const, category: "attractions" as const, keywords: ["deepest pool world", "Deep Dive Dubai record"] },
  { title: "Ain Dubai Returns", headlineAngle: "World's Tallest Observation Wheel (250m)", viralPotential: "5" as const, format: "pov_video" as const, topicType: "trending" as const, mainCategory: "records_superlatives" as const, category: "attractions" as const, keywords: ["Ain Dubai", "Dubai Eye wheel"] },
  { title: "Dubai Police Bugatti", headlineAngle: "World's Fastest Police Car", viralPotential: "5" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "records_superlatives" as const, category: "tips" as const, keywords: ["Dubai police Bugatti", "fastest police car"] },
  { title: "Dubai Miracle Garden Records", headlineAngle: "150 Million Blooms, World's Largest Floral Structure", viralPotential: "4" as const, format: "drone_footage" as const, topicType: "seasonal" as const, mainCategory: "records_superlatives" as const, category: "attractions" as const, keywords: ["Miracle Garden records", "largest flower garden"] },
  { title: "Palm Jumeirah Engineering", headlineAngle: "World's Largest Man-Made Island", viralPotential: "5" as const, format: "documentary" as const, topicType: "evergreen" as const, mainCategory: "records_superlatives" as const, category: "attractions" as const, keywords: ["Palm Jumeirah facts", "how Palm built"] },
  { title: "Dubai Mall Statistics", headlineAngle: "1,200 Shops, 33,000 Fish, Olympic Rink", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "records_superlatives" as const, category: "shopping" as const, keywords: ["Dubai Mall facts", "biggest mall statistics"] },
  { title: "Dubai Frame 150m", headlineAngle: "World's Largest Picture Frame", viralPotential: "4" as const, format: "pov_video" as const, topicType: "evergreen" as const, mainCategory: "records_superlatives" as const, category: "attractions" as const, keywords: ["Dubai Frame record", "largest frame world"] },
  { title: "Drone Show Records", headlineAngle: "4,000 Drones, 3 Guinness Records in One Night", viralPotential: "5" as const, format: "video_tour" as const, topicType: "trending" as const, mainCategory: "records_superlatives" as const, category: "events" as const, keywords: ["Dubai drone show", "drone record Dubai"] },

  // ===== FUTURE & DEVELOPMENT (15 Topics) =====
  { title: "Dubai Creek Tower", headlineAngle: "The New World's Tallest Building Coming", viralPotential: "5" as const, format: "documentary" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "news" as const, keywords: ["Dubai Creek Tower", "tallest building 2025"] },
  { title: "Flying Taxis 2026", headlineAngle: "Dubai's Air Taxi Network Is Actually Happening", viralPotential: "5" as const, format: "explainer" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "news" as const, keywords: ["Dubai flying taxi", "air taxi Dubai"] },
  { title: "Dubai 2040 Master Plan", headlineAngle: "Population Doubling to 7.8 Million", viralPotential: "4" as const, format: "infographic" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "news" as const, keywords: ["Dubai 2040", "Dubai future plan"] },
  { title: "Al Maktoum Airport Expansion", headlineAngle: "World's Largest Airport (5x Current)", viralPotential: "5" as const, format: "infographic" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "news" as const, keywords: ["Al Maktoum Airport", "Dubai new airport"] },
  { title: "Burj Binghatti 2026", headlineAngle: "World's Tallest Residential Tower", viralPotential: "4" as const, format: "documentary" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "news" as const, keywords: ["Burj Binghatti", "tallest residential Dubai"] },
  { title: "Dubai Reefs Floating City", headlineAngle: "200 sq m Artificial Reef for Conservation", viralPotential: "5" as const, format: "documentary" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "news" as const, keywords: ["Dubai Reefs project", "floating city Dubai"] },
  { title: "The Loop 93km Walking Highway", headlineAngle: "Climate-Controlled Pedestrian Network", viralPotential: "4" as const, format: "documentary" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "news" as const, keywords: ["The Loop Dubai", "Dubai walking highway"] },
  { title: "Dubai Metro Blue Line", headlineAngle: "30km, 14 Stations Connecting 9 Districts", viralPotential: "4" as const, format: "infographic" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "transport" as const, keywords: ["Dubai Metro Blue Line", "new metro Dubai"] },
  { title: "Therme Dubai AED 2 Billion", headlineAngle: "Year-Round Wellness Mega Resort", viralPotential: "4" as const, format: "documentary" as const, topicType: "trending" as const, mainCategory: "future_development" as const, category: "attractions" as const, keywords: ["Therme Dubai", "Dubai wellness resort"] },
  { title: "Expo City Dubai Legacy", headlineAngle: "What's Left After the World Expo", viralPotential: "4" as const, format: "video_tour" as const, topicType: "evergreen" as const, mainCategory: "future_development" as const, category: "attractions" as const, keywords: ["Expo City Dubai", "Dubai Expo 2020 legacy"] },

  // ===== SEASONAL & EVENTS (12 Topics) =====
  { title: "Best Time to Visit Guide", headlineAngle: "Complete Month-by-Month Breakdown", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "seasonal_events" as const, category: "tips" as const, keywords: ["best time Dubai", "when to visit Dubai"] },
  { title: "Summer Survival Guide", headlineAngle: "How to Beat 50°C Heat", viralPotential: "5" as const, format: "guide" as const, topicType: "seasonal" as const, mainCategory: "seasonal_events" as const, category: "tips" as const, keywords: ["Dubai summer tips", "Dubai heat survival"] },
  { title: "Dubai Shopping Festival", headlineAngle: "30th Anniversary: 75% Discounts, Drone Shows", viralPotential: "5" as const, format: "guide" as const, topicType: "seasonal" as const, mainCategory: "seasonal_events" as const, category: "shopping" as const, keywords: ["Dubai Shopping Festival 2025", "DSF Dubai"] },
  { title: "Ramadan for Tourists 2025", headlineAngle: "The Complete Guide for Visitors", viralPotential: "5" as const, format: "guide" as const, topicType: "seasonal" as const, mainCategory: "seasonal_events" as const, category: "tips" as const, keywords: ["Ramadan Dubai tourists", "visiting Dubai Ramadan"] },
  { title: "NYE World's Most Epic Fireworks", headlineAngle: "Where to Watch Burj Khalifa Display", viralPotential: "5" as const, format: "guide" as const, topicType: "seasonal" as const, mainCategory: "seasonal_events" as const, category: "events" as const, keywords: ["Dubai New Year fireworks", "Burj Khalifa NYE"] },
  { title: "Dubai Events Calendar 2025", headlineAngle: "What's Happening Every Month", viralPotential: "4" as const, format: "guide" as const, topicType: "seasonal" as const, mainCategory: "seasonal_events" as const, category: "events" as const, keywords: ["Dubai events 2025", "Dubai calendar"] },
  { title: "Winter in Dubai (Nov-Feb)", headlineAngle: "The Perfect Weather Window", viralPotential: "4" as const, format: "guide" as const, topicType: "seasonal" as const, mainCategory: "seasonal_events" as const, category: "tips" as const, keywords: ["Dubai winter", "best season Dubai"] },
  { title: "Christmas in Dubai", headlineAngle: "Decorations, Markets, Festive Events", viralPotential: "4" as const, format: "guide" as const, topicType: "seasonal" as const, mainCategory: "seasonal_events" as const, category: "events" as const, keywords: ["Christmas Dubai", "Dubai festive season"] },
  { title: "Eid Celebrations", headlineAngle: "How Dubai Celebrates Like Nowhere Else", viralPotential: "4" as const, format: "video_tour" as const, topicType: "seasonal" as const, mainCategory: "seasonal_events" as const, category: "events" as const, keywords: ["Eid Dubai", "Dubai Eid celebrations"] },

  // ===== PRACTICAL & TIPS (18 Topics) =====
  { title: "10 Tourist Mistakes to Avoid", headlineAngle: "PDA, Drinking in Public, Photography Rules", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai tourist mistakes", "things not to do Dubai"] },
  { title: "Dubai Dress Code Visual Guide", headlineAngle: "What You CAN and CAN'T Wear", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai dress code", "what to wear Dubai"] },
  { title: "Dubai Scams to Avoid", headlineAngle: "Unofficial Taxis, Fake Gold, ATM Skimmers", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai scams", "tourist scams Dubai"] },
  { title: "Complete Transport Guide", headlineAngle: "Metro, Abra, Taxi, Apps", viralPotential: "4" as const, format: "tutorial" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "transport" as const, keywords: ["Dubai transport guide", "getting around Dubai"] },
  { title: "Packing Essentials", headlineAngle: "What to Bring (and Leave Behind)", viralPotential: "4" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai packing list", "what to pack Dubai"] },
  { title: "SIM Card & Connectivity Guide", headlineAngle: "Free Airport SIM, eSIM Options", viralPotential: "4" as const, format: "tutorial" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai SIM card", "internet Dubai tourist"] },
  { title: "Laws That Could Get You Arrested", headlineAngle: "Zero Tolerance Rules to Know", viralPotential: "5" as const, format: "list_video" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai laws tourists", "illegal in Dubai"] },
  { title: "Best Areas to Stay", headlineAngle: "First-Timer Location Guide", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "hotels" as const, keywords: ["where to stay Dubai", "best area Dubai tourist"] },
  { title: "Visa Guide by Nationality", headlineAngle: "Everything You Need to Know", viralPotential: "4" as const, format: "explainer" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai visa guide", "UAE visa requirements"] },
  { title: "First 24 Hours Itinerary", headlineAngle: "What to Do When You Land", viralPotential: "5" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["first day Dubai", "Dubai itinerary day 1"] },
  { title: "Photography Rules", headlineAngle: "What NOT to Photograph", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai photography rules", "can I take photos Dubai"] },
  { title: "Dubai Metro Etiquette", headlineAngle: "Avoid These Fines", viralPotential: "4" as const, format: "tutorial" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "transport" as const, keywords: ["Dubai metro rules", "metro fines Dubai"] },
  { title: "Health & Safety Tips", headlineAngle: "Insurance, Banned Medications, Heat", viralPotential: "4" as const, format: "guide" as const, topicType: "evergreen" as const, mainCategory: "practical_tips" as const, category: "tips" as const, keywords: ["Dubai health tips", "travel insurance Dubai"] },
];

async function seedViralTopics() {
  console.log("🚀 Starting to seed 200+ viral Dubai topics...\n");

  let inserted = 0;
  let skipped = 0;

  for (const topic of viralTopics) {
    try {
      await db.insert(topicBank).values({
        title: topic.title,
        headlineAngle: topic.headlineAngle,
        category: topic.category,
        mainCategory: topic.mainCategory,
        viralPotential: topic.viralPotential,
        format: topic.format,
        topicType: topic.topicType,
        keywords: topic.keywords,
        priority: topic.viralPotential === "5" ? 100 : topic.viralPotential === "4" ? 75 : 50,
        isActive: true,
      });
      inserted++;
      console.log(`✅ Added: ${topic.title}`);
    } catch (error: any) {
      if (error.code === '23505') { // Unique constraint violation
        skipped++;
        console.log(`⏭️ Skipped (exists): ${topic.title}`);
      } else {
        console.error(`❌ Error adding ${topic.title}:`, error.message);
      }
    }
  }

  console.log(`\n📊 Summary:`);
  console.log(`   ✅ Inserted: ${inserted}`);
  console.log(`   ⏭️ Skipped: ${skipped}`);
  console.log(`   📝 Total topics: ${viralTopics.length}`);
}

seedViralTopics()
  .then(() => {
    console.log("\n🎉 Done seeding viral topics!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Fatal error:", error);
    process.exit(1);
  });
