import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import {
  Link2,
  LinkIcon,
  ExternalLink,
  AlertTriangle,
  TrendingUp,
  Target,
  Loader2,
  RefreshCw,
  Play,
  FileText,
  Activity,
} from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

interface LinkHealthMetrics {
  totalLinks: number;
  autoGeneratedLinks: number;
  manualLinks: number;
  averageOutboundPerPage: number;
  orphanPageCount: number;
  pagesWithLinks: number;
  totalPages: number;
}

interface OrphanPage {
  id: string;
  title: string;
  type: string;
  slug: string;
}

interface TopLinkedPage {
  contentId: string;
  inboundCount: number;
  title: string;
  type: string;
  slug: string;
}

interface RecentLink {
  id: string;
  sourceContentId: string;
  targetContentId: string;
  anchorText: string;
  isAutoSuggested: boolean;
  createdAt: string;
}

export default function LinksDashboard() {
  const { toast } = useToast();

  const { data: healthData, isLoading: healthLoading, refetch: refetchHealth } = useQuery<{
    success: boolean;
    data: LinkHealthMetrics;
  }>({
    queryKey: ["/api/links/health"],
    refetchInterval: 30000,
  });

  const { data: orphansData, isLoading: orphansLoading } = useQuery<{
    success: boolean;
    data: { count: number; pages: OrphanPage[] };
  }>({
    queryKey: ["/api/links/orphans"],
  });

  const { data: topLinkedData, isLoading: topLinkedLoading } = useQuery<{
    success: boolean;
    data: TopLinkedPage[];
  }>({
    queryKey: ["/api/links/top-linked"],
  });

  const { data: recentData, isLoading: recentLoading } = useQuery<{
    success: boolean;
    data: RecentLink[];
  }>({
    queryKey: ["/api/links/recent"],
  });

  const processLinksMutation = useMutation({
    mutationFn: async (contentId: string) => {
      const response = await apiRequest("POST", `/api/links/process/${contentId}`);
      return response.json();
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: ["/api/links"] });
      toast({
        title: "Links Processed",
        description: `Added ${result.data?.linksAdded || 0} internal links`,
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Processing Failed",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const metrics = healthData?.data;
  const orphans = orphansData?.data?.pages || [];
  const topLinked = topLinkedData?.data || [];
  const recentLinks = recentData?.data || [];

  const isLoading = healthLoading || orphansLoading || topLinkedLoading || recentLoading;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin" data-testid="loader-main" />
      </div>
    );
  }

  const linkCoverage = metrics && metrics.totalPages > 0
    ? ((metrics.pagesWithLinks / metrics.totalPages) * 100).toFixed(1)
    : "0";

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-bold" data-testid="text-page-title">
            Internal Links Management
          </h1>
          <p className="text-muted-foreground">
            Monitor and manage internal linking for SEO optimization
          </p>
        </div>
        <Button
          variant="outline"
          onClick={() => refetchHealth()}
          data-testid="button-refresh"
        >
          <RefreshCw className="h-4 w-4 mr-2" />
          Refresh
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card data-testid="card-total-links">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
            <CardTitle className="text-sm font-medium">Total Links</CardTitle>
            <Link2 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{metrics?.totalLinks || 0}</div>
            <p className="text-xs text-muted-foreground">
              {metrics?.autoGeneratedLinks || 0} auto-generated
            </p>
          </CardContent>
        </Card>

        <Card data-testid="card-link-coverage">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
            <CardTitle className="text-sm font-medium">Link Coverage</CardTitle>
            <Target className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{linkCoverage}%</div>
            <p className="text-xs text-muted-foreground">
              {metrics?.pagesWithLinks || 0} / {metrics?.totalPages || 0} pages
            </p>
          </CardContent>
        </Card>

        <Card data-testid="card-orphan-pages">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
            <CardTitle className="text-sm font-medium">Orphan Pages</CardTitle>
            <AlertTriangle className="h-4 w-4 text-yellow-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-yellow-600">
              {metrics?.orphanPageCount || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              Pages without inbound links
            </p>
          </CardContent>
        </Card>

        <Card data-testid="card-avg-links">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 gap-2">
            <CardTitle className="text-sm font-medium">Avg Links/Page</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {(metrics?.averageOutboundPerPage || 0).toFixed(1)}
            </div>
            <p className="text-xs text-muted-foreground">
              Target: 3-5 links per page
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card data-testid="card-orphan-pages-list">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-yellow-500" />
              Orphan Pages (No Inbound Links)
            </CardTitle>
            <CardDescription>
              Pages that have no internal links pointing to them
            </CardDescription>
          </CardHeader>
          <CardContent>
            {orphans.length === 0 ? (
              <p className="text-muted-foreground text-center py-4">
                No orphan pages found
              </p>
            ) : (
              <div className="space-y-2 max-h-80 overflow-y-auto">
                {orphans.slice(0, 10).map((page) => (
                  <div
                    key={page.id}
                    className="flex items-center justify-between p-2 border rounded"
                    data-testid={`orphan-page-${page.id}`}
                  >
                    <div className="flex items-center gap-2">
                      <FileText className="h-4 w-4 text-muted-foreground" />
                      <div>
                        <p className="text-sm font-medium">{page.title}</p>
                        <p className="text-xs text-muted-foreground">
                          {page.type} • {page.slug}
                        </p>
                      </div>
                    </div>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => processLinksMutation.mutate(page.id)}
                      disabled={processLinksMutation.isPending}
                      data-testid={`button-process-${page.id}`}
                    >
                      <Play className="h-3 w-3 mr-1" />
                      Add Links
                    </Button>
                  </div>
                ))}
                {orphans.length > 10 && (
                  <p className="text-xs text-muted-foreground text-center">
                    +{orphans.length - 10} more orphan pages
                  </p>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        <Card data-testid="card-top-linked">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-green-500" />
              Top Linked Pages
            </CardTitle>
            <CardDescription>
              Pages with the most inbound internal links
            </CardDescription>
          </CardHeader>
          <CardContent>
            {topLinked.length === 0 ? (
              <p className="text-muted-foreground text-center py-4">
                No link data available
              </p>
            ) : (
              <div className="space-y-2 max-h-80 overflow-y-auto">
                {topLinked.map((page, index) => (
                  <div
                    key={page.contentId}
                    className="flex items-center justify-between p-2 border rounded"
                    data-testid={`top-linked-${page.contentId}`}
                  >
                    <div className="flex items-center gap-2">
                      <Badge variant="outline">{index + 1}</Badge>
                      <div>
                        <p className="text-sm font-medium">{page.title}</p>
                        <p className="text-xs text-muted-foreground">
                          {page.type}
                        </p>
                      </div>
                    </div>
                    <Badge variant="secondary">
                      {page.inboundCount} links
                    </Badge>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card data-testid="card-recent-links">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Activity className="h-5 w-5" />
            Recent Links Added
          </CardTitle>
          <CardDescription>
            Most recently created internal links
          </CardDescription>
        </CardHeader>
        <CardContent>
          {recentLinks.length === 0 ? (
            <p className="text-muted-foreground text-center py-4">
              No recent links
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Anchor Text</TableHead>
                  <TableHead>Source</TableHead>
                  <TableHead>Target</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Created</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {recentLinks.slice(0, 15).map((link) => (
                  <TableRow key={link.id} data-testid={`recent-link-${link.id}`}>
                    <TableCell className="font-medium">
                      {link.anchorText || "-"}
                    </TableCell>
                    <TableCell className="text-xs text-muted-foreground">
                      {link.sourceContentId?.substring(0, 8)}...
                    </TableCell>
                    <TableCell className="text-xs text-muted-foreground">
                      {link.targetContentId?.substring(0, 8)}...
                    </TableCell>
                    <TableCell>
                      <Badge variant={link.isAutoSuggested ? "secondary" : "outline"}>
                        {link.isAutoSuggested ? "Auto" : "Manual"}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-xs text-muted-foreground">
                      {link.createdAt
                        ? formatDistanceToNow(new Date(link.createdAt), { addSuffix: true })
                        : "-"}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
